### ISSUE TITLE
Method to export to Confluence 

### ISSUE THREAD

**Issue by waghcwb** [Shogobg/markdown2confluence#10]
It will be greate if the tool automatic export to confluence

**Comment by Shogobg** [comment]
Hello @waghcwb , this is a good idea!

Unfortunately, I do not have enough time to implement it right now.
If you can submit a pull request, I would gladly review it and merge the change to this repository!

**Comment by Shogobg** [comment]
Closing this one as there is no plan to support this feature right now.
There's packages to work with the confluence API, please use them instead,
