### ISSUE TITLE
SyntaxError: Unexpected token '?'

### ISSUE THREAD

**Issue by javimsevilla** [Shogobg/markdown2confluence#3]
Hi,

I ran into a syntax error while trying markdown2confluence from the [npm official registry published version](https://www.npmjs.com/package/@shogobg/markdown2confluence).

### Visual proof

![image](https://user-images.githubusercontent.com/3058446/110250632-96f14a80-7f7c-11eb-8b98-8ff71ba7fdca.png)

### Expected results vs actual results

I expected to get the transformed markdown text output but received this syntax error:

```
lang = defaultLanguageMap[(lang ?? '').toLowerCase()];
                                 ^
SyntaxError: Unexpected token '?'
```

### Steps to reproduce

1. Installed from official registry: `npm i -g @shogobg/markdown2confluence`
2. Created an `example.md` file in my desktop:

```
# Header 1

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras malesuada tristique mauris, in dapibus est.
```

3. Opened a command line on desktop and execute this command:

```
markdown2confluence example.md
```

4. The command response is:

```
C:\Users\username\AppData\Roaming\nvm\v12.18.4\node_modules\@shogobg\markdown2confluence\index.js:380
    lang = defaultLanguageMap[(lang ?? '').toLowerCase()];
                                     ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\username\AppData\Roaming\nvm\v12.18.4\node_modules\@shogobg\markdown2confluence\bin\markdown2confluence.js:2:17)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
```

### Environment

- Node.js version: `v12.18.4`
- npm version: `6.14.6`

### Other info

I think it is caused by the [Nullish coalescing Javascript operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator) at [index.js#L380](https://github.com/Shogobg/markdown2confluence/blob/934266c3b0c01c7f80de11f21a1177e489275f18/index.js#L380). Maybe my Node.js version does not support it yet?

Thank you!

**Comment by Shogobg** [comment]
Hello @javimsevilla ,

thanks for filing this bug report.

You are right - this issue comes from Node.js not supporting null coalescing until version 14.
Is it possible for you to update your Node.js?

**Comment by javimsevilla** [comment]
Hi! Thank you for your fast response! I use [coreybutler/mvn-windows](https://github.com/coreybutler/nvm-windows) (Node Version Manager for Windows) so I can try it easily and give you feedback soon (or so I hope!).

**Comment by javimsevilla** [comment]
Just updated Node.js to v14.16.0 and now it works! Thank you ✔
