### ISSUE TITLE
It works with Confluence Cloud syntax?

### ISSUE THREAD

**Issue by javimsevilla** [Shogobg/markdown2confluence#4]
Hi 👋🏻,

I would like to know if the output generated by this CLI works with the Confluence Cloud content creation syntax.

Thank you very much 😃 .

**Comment by Shogobg** [comment]
Hello @javimsevilla ,
yes, it should work with Confluence Cloud.
If you see a tag that's being translated incorrectly, let me know and I'll see to fixing it.
