### ISSUE TITLE
Quotation mark and some other characters shows up encoded

### ISSUE THREAD

**Issue by vill3t** [Shogobg/markdown2confluence#8]
Hi, some of the special characters are showing encoded after conversion, except in code block - that renders it correctly.

Some examples:

Quotation mark `"` will be after conversion `&quot;`
Apostrophe `'` will be after conversion `&#39;`

**Comment by Shogobg** [comment]
Hello @virefined, this is expected behavior.
This library will convert your markdown in a format suitable for use with confluence wiki markup style.
If you use the Markup feature and select Confluence wiki, the encoded characters will be automatically converted for you.
